Website = "https://github.com/ytget/yt-downloader"

[Details]
  Icon = "yt-downloader.png"
  Name = "YT Downloader"
  ID = "com.github.ytget.ytdownloader"
  Version = "1.0.0"
  Build = 205

[LinuxAndBSD]
  GenericName = "YouTube Video Downloader"
  Categories = ["Network", "Video", "Audio"]
  Comment = "Download videos and playlists from YouTube and other platforms"
  Keywords = ["youtube", "download", "video", "playlist", "audio", "converter"]
