name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Install tools
        run: |
          go install fyne.io/tools/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build (Linux/Windows/Android)
        run: |
          export VERSION="${GITHUB_REF_NAME#v}"
          make build-linux-amd64
          make build-windows-amd64
          make build-android

      - name: Upload artifacts (ubuntu)
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-ubuntu
          path: fyne-cross/dist/**
          if-no-files-found: error

  build-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Install tools
        run: |
          go install fyne.io/tools/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Build (macOS)
        run: |
          export VERSION="${GITHUB_REF_NAME#v}"
          make package-darwin
          make collect-artifacts

      - name: Upload artifacts (darwin)
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-darwin
          path: |
            fyne-cross/dist/**
            dist/**
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-darwin]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Generate checksums
        run: |
          cd artifacts
          find . -type f -print0 | xargs -0 shasum -a 256 > SHA256SUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


